# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.7.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.7.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sundongxu/Code/Git/Mine/Learning/Alg-DS/libbcrypt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sundongxu/Code/Git/Mine/Learning/Alg-DS/libbcrypt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/Cellar/cmake/3.7.1/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.7.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.7.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/Cellar/cmake/3.7.1/bin/cpack --config ./CPackSourceConfig.cmake /Users/sundongxu/Code/Git/Mine/Learning/Alg-DS/libbcrypt/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sundongxu/Code/Git/Mine/Learning/Alg-DS/libbcrypt/CMakeFiles /Users/sundongxu/Code/Git/Mine/Learning/Alg-DS/libbcrypt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sundongxu/Code/Git/Mine/Learning/Alg-DS/libbcrypt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bcrypt

# Build rule for target.
bcrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bcrypt
.PHONY : bcrypt

# fast build rule for target.
bcrypt/fast:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/build
.PHONY : bcrypt/fast

#=============================================================================
# Target rules for targets named bcrypt_test

# Build rule for target.
bcrypt_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bcrypt_test
.PHONY : bcrypt_test

# fast build rule for target.
bcrypt_test/fast:
	$(MAKE) -f CMakeFiles/bcrypt_test.dir/build.make CMakeFiles/bcrypt_test.dir/build
.PHONY : bcrypt_test/fast

src/bcrypt.o: src/bcrypt.c.o

.PHONY : src/bcrypt.o

# target to build an object file
src/bcrypt.c.o:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/bcrypt.c.o
.PHONY : src/bcrypt.c.o

src/bcrypt.i: src/bcrypt.c.i

.PHONY : src/bcrypt.i

# target to preprocess a source file
src/bcrypt.c.i:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/bcrypt.c.i
.PHONY : src/bcrypt.c.i

src/bcrypt.s: src/bcrypt.c.s

.PHONY : src/bcrypt.s

# target to generate assembly for a file
src/bcrypt.c.s:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/bcrypt.c.s
.PHONY : src/bcrypt.c.s

src/crypt_blowfish.o: src/crypt_blowfish.c.o

.PHONY : src/crypt_blowfish.o

# target to build an object file
src/crypt_blowfish.c.o:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/crypt_blowfish.c.o
.PHONY : src/crypt_blowfish.c.o

src/crypt_blowfish.i: src/crypt_blowfish.c.i

.PHONY : src/crypt_blowfish.i

# target to preprocess a source file
src/crypt_blowfish.c.i:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/crypt_blowfish.c.i
.PHONY : src/crypt_blowfish.c.i

src/crypt_blowfish.s: src/crypt_blowfish.c.s

.PHONY : src/crypt_blowfish.s

# target to generate assembly for a file
src/crypt_blowfish.c.s:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/crypt_blowfish.c.s
.PHONY : src/crypt_blowfish.c.s

src/crypt_gensalt.o: src/crypt_gensalt.c.o

.PHONY : src/crypt_gensalt.o

# target to build an object file
src/crypt_gensalt.c.o:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/crypt_gensalt.c.o
.PHONY : src/crypt_gensalt.c.o

src/crypt_gensalt.i: src/crypt_gensalt.c.i

.PHONY : src/crypt_gensalt.i

# target to preprocess a source file
src/crypt_gensalt.c.i:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/crypt_gensalt.c.i
.PHONY : src/crypt_gensalt.c.i

src/crypt_gensalt.s: src/crypt_gensalt.c.s

.PHONY : src/crypt_gensalt.s

# target to generate assembly for a file
src/crypt_gensalt.c.s:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/crypt_gensalt.c.s
.PHONY : src/crypt_gensalt.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bcrypt_test.dir/build.make CMakeFiles/bcrypt_test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bcrypt_test.dir/build.make CMakeFiles/bcrypt_test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bcrypt_test.dir/build.make CMakeFiles/bcrypt_test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/wrapper.o: src/wrapper.c.o

.PHONY : src/wrapper.o

# target to build an object file
src/wrapper.c.o:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/wrapper.c.o
.PHONY : src/wrapper.c.o

src/wrapper.i: src/wrapper.c.i

.PHONY : src/wrapper.i

# target to preprocess a source file
src/wrapper.c.i:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/wrapper.c.i
.PHONY : src/wrapper.c.i

src/wrapper.s: src/wrapper.c.s

.PHONY : src/wrapper.s

# target to generate assembly for a file
src/wrapper.c.s:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/wrapper.c.s
.PHONY : src/wrapper.c.s

src/x86.o: src/x86.S.o

.PHONY : src/x86.o

# target to build an object file
src/x86.S.o:
	$(MAKE) -f CMakeFiles/bcrypt.dir/build.make CMakeFiles/bcrypt.dir/src/x86.S.o
.PHONY : src/x86.S.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... bcrypt"
	@echo "... package"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... bcrypt_test"
	@echo "... src/bcrypt.o"
	@echo "... src/bcrypt.i"
	@echo "... src/bcrypt.s"
	@echo "... src/crypt_blowfish.o"
	@echo "... src/crypt_blowfish.i"
	@echo "... src/crypt_blowfish.s"
	@echo "... src/crypt_gensalt.o"
	@echo "... src/crypt_gensalt.i"
	@echo "... src/crypt_gensalt.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/wrapper.o"
	@echo "... src/wrapper.i"
	@echo "... src/wrapper.s"
	@echo "... src/x86.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

